version: "3.7"
services:
  v2ray-client:
    image: v2fly/v2fly-core
    container_name: v2ray-client
    ports:
      - 1080:1080
      - 1081:1081
    command: run -c /etc/v2ray/config.json
    volumes:
      - ./v2ray-client.json:/etc/v2ray/config.json
    restart: unless-stopped
